<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?php $editing = $task !== null; $errors = session('errors') ?? []; ?>
<section class="form-page"><div class="form-intro"><a class="back-link" href="<?= site_url('tasks') ?>">← Back to tasks</a><div class="eyebrow"><span class="eyebrow-dot"></span> <?= $editing ? 'Shape your next step' : 'A fresh start' ?></div><h1><?= $editing ? 'Edit this ' : 'Create a ' ?><em>task.</em></h1><p>Give it a clear name and a date. The rest can take shape as you go.</p><div class="form-art" aria-hidden="true"><span>✦</span><i></i><i></i></div></div>
<div class="form-card"><div class="form-card-header"><span><?= $editing ? 'Task details' : 'New task details' ?></span><span class="required-note">* Required fields</span></div><form action="<?= esc($formAction, 'attr') ?>" method="post" novalidate><?= csrf_field() ?>
    <div class="field"><label for="title">Task title <b>*</b></label><input id="title" name="title" type="text" maxlength="180" required placeholder="What needs to get done?" value="<?= esc(old('title', $task['title'] ?? ''), 'attr') ?>" aria-describedby="title-error"><small id="title-error" class="field-error"><?= esc($errors['title'] ?? '') ?></small></div>
    <div class="field"><label for="description">Description <span>Optional</span></label><textarea id="description" name="description" rows="4" maxlength="2000" placeholder="Add a little context for later..."><?= esc(old('description', $task['description'] ?? '')) ?></textarea><small class="field-error"><?= esc($errors['description'] ?? '') ?></small></div>
    <div class="field-row"><div class="field"><label for="task_date">Due date <b>*</b></label><input id="task_date" name="task_date" type="date" required value="<?= esc(old('task_date', $task['task_date'] ?? date('Y-m-d')), 'attr') ?>"><small class="field-error"><?= esc($errors['task_date'] ?? '') ?></small></div><div class="field"><label for="priority">Priority</label><select id="priority" name="priority"><?php foreach (['Low', 'Normal', 'High'] as $priority): ?><option value="<?= $priority ?>" <?= old('priority', $task['priority'] ?? 'Normal') === $priority ? 'selected' : '' ?>><?= $priority ?></option><?php endforeach; ?></select><small class="field-error"><?= esc($errors['priority'] ?? '') ?></small></div></div>
    <div class="field"><label for="status">Status</label><select id="status" name="status"><?php foreach (['To do', 'In progress', 'Done'] as $status): ?><option value="<?= $status ?>" <?= old('status', $task['status'] ?? 'To do') === $status ? 'selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select><small class="field-error"><?= esc($errors['status'] ?? '') ?></small></div>
    <div class="form-actions"><a href="<?= site_url('tasks') ?>" class="button button-ghost">Cancel</a><button type="submit" class="button"><?= $editing ? 'Save changes' : 'Create task' ?> <span aria-hidden="true">↗</span></button></div>
</form></div></section>
<?= $this->endSection() ?>
